//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PyrokinesisPets.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albom
    {
        public int Id { get; set; }
        public Nullable<int> Id_Pet { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
    
        public virtual TypePets TypePets { get; set; }
    }
}
